### ISSUE TITLE
Err_File_Not_Found

### ISSUE THREAD

**Issue by eyeball29** [iamtheyammer/fetch-ford-service-manuals#12]
Receiving an error partway through the process. Got through three sections and then this appears:

```
Downloading manual page Four-Wheel Drive Systems - Overview.html (docID: G1582404)
C:\savingstuffhere\src\saveEntireManual.ts:115
  await page.goto(`file://${htmlPath}`, { waitUntil: "load" });
             ^
page.goto: net::ERR_FILE_NOT_FOUND at file:///C:/savingstuffhere/3-%20Powertrain/08-%20Manual%20Transmission,%20Clutch,%20Transfer%20Case%20and%20Power%20Transfer%20Unit/308-07A%20Four-Wheel%20Drive%20Systems%20-%20Vehicles%20With-%20Active%20Torque%20Coupling%20Differential/Description%20and%20Operation/Four-Wheel%20Drive%20Systems%20-%20Overview.html
=========================== logs ===========================
navigating to "file:///C:/savingstuffhere/3-%20Powertrain/08-%20Manual%20Transmission,%20Clutch,%20Transfer%20Case%20and%20Power%20Transfer%20Unit/308-07A%20Four-Wheel%20Drive%20Systems%20-%20Vehicles%20With-%20Active%20Torque%20Coupling%20Differential/Description%20and%20Operation/Four-Wheel%20Drive%20Systems%20-%20Overview.html", waiting until "load"
============================================================
    at savePageAsPDF (C:\savingstuffhere\fetch-ford-service-manuals\src\saveEntireManual.ts:115:14)
    at saveEntireManual (C:\savingstuffhere\fetch-ford-service-manuals\src\saveEntireManual.ts:86:13)
    at async saveEntireManual (C:\savingstuffhere\fetch-ford-service-manuals\src\saveEntireManual.ts:105:7)
    at async saveEntireManual (C:\savingstuffhere\fetch-ford-service-manuals\src\saveEntireManual.ts:105:7)
    at async saveEntireManual (C:\savingstuffhere\fetch-ford-service-manuals\src\saveEntireManual.ts:105:7)
    at async saveEntireManual (C:\savingstuffhere\fetch-ford-service-manuals\src\saveEntireManual.ts:105:7)
    at async run (C:\savingstuffhere\fetch-ford-service-manuals\src\index.ts:59:3) {
  name: 'Error'
}
```

**Comment by eyeball29** [comment]
Is there a way to skip a particular file? Looks like it might keep going if I can get past that one.

**Comment by iamtheyammer** [comment]
I can definitely add a method for it to skip files and just move on— but could you check if that file indeed does exist?

`C:/3- Powertrain/08- Manual Transmission, Clutch, Transfer Case and Power Transfer Unit/308-07A Four-Wheel Drive Systems - Vehicles With- Active Torque Coupling Differential/Description and Operation/Four-Wheel Drive Systems - Overview.html`

**Comment by iamtheyammer** [comment]
The better solution is to use the browser exclusively to load all the pages and use that to save both the HTML and PDF, but I recall that causing a bunch of problems. How long is your subscription valid for?

**Comment by eyeball29** [comment]
It appeared to exist on the site and have the correct docID: G1582404 associated... But I think you meant on my drive? I'd have to check when I get home. 

My subscription ends today I believe but I should be able to keep attempting as long as the cookie data is relatively recent, correct? If not, I'll pay the extra to extend it... Still better than the amount for monthly or the eBay ones.

**Comment by eyeball29** [comment]
I have confirmed that the 
/3- Powertrain/08- Manual Transmission, Clutch, Transfer Case and Power Transfer Unit/308-07A Four-Wheel Drive Systems - Vehicles With- Active Torque Coupling Differential/Description and Operation/Four-Wheel Drive Systems - Overview.html
file exists within the files downloaded, just not the PDF.

**Comment by RedxRabbit** [comment]
`yadvinder@DESKTOP-SE907EF:~/fetch-ford-service-manuals$ yarn start -c templates/params.json -s templates/cookieString.txt -o /C:/Users/Yadvinder Gill/Desktop/New folder/
UNKNOWN_VALUE: Unknown value: Gill/Desktop/New
    at commandLineArgs (/home/yadvinder/fetch-ford-service-manuals/.yarn/cache/command-line-args-npm-5.2.1-093a68d295-e6a42652ae.zip/node_modules/command-line-args/dist/index.js:1369:21)
    at processCLIArgs (/home/yadvinder/fetch-ford-service-manuals/src/processCLIArgs.ts:70:36)
    at Object.<anonymous> (/home/yadvinder/fetch-ford-service-manuals/src/index.ts:113:28)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/home/yadvinder/fetch-ford-service-manuals/.yarn/__virtual__/ts-node-virtual-6ff420c4ac/0/cache/ts-node-npm-10.7.0-ef39b1d45e-5c2b3a43ea.zip/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at require$$0.Module._extensions..js (/home/yadvinder/fetch-ford-service-manuals/.pnp.cjs:7233:33)
    at Object.require.extensions.<computed> [as .ts] (/home/yadvinder/fetch-ford-service-manuals/.yarn/__virtual__/ts-node-virtual-6ff420c4ac/0/cache/ts-node-npm-10.7.0-ef39b1d45e-5c2b3a43ea.zip/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12) {
  value: 'Gill/Desktop/New'
}

Ford Workshop Manual Downloader

  Download the full Ford workshop manual for your car. Must have a valid PTS
  subscription.

Options

  --configFile -c /path/to/config.json          Required. Path to your config file.
  --cookieString -s /path/to/cookieString.txt   Required. Path to the file that contains your PTS Cookie Header.
  --outputPath -o /path/for/manual              Required. Directory where you'd like the manual to download to. Should be an
                                                empty directory.
  --help string                                 Print this usage guide.`

**Comment by RedxRabbit** [comment]
I am getting this error, what did I do wrong?

**Comment by RedxRabbit** [comment]
I am having the same issue, please help

**Comment by iamtheyammer** [comment]
Should be fixed in the newest commit. The way I re-wrote the saving code no longer automatically saves HTML files by default— add `—saveHTML` to do so.
