### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

### ISSUE THREAD

**Issue by woliver99** [iamtheyammer/fetch-ford-service-manuals#13]
I saw that there was already a problem with this but the issue was closed and reading it didnt provide me with a solution. Anyway im running wsl on windows 10 and the script starts downloading fine but after about 20 minutes it pops with this error:

```
Downloading manual page Front Subframe - 5.0L 32V Ti-VCT/5.2L 32V Ti-VCT – Supercharged.html (docID: G2104497)
Downloading manual page Rear Subframe.html (docID: G1686636)
Downloading manual page Transmission Support Crossmember.html (docID: G1686637)
Saving wiring manual...
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
    at ClientRequest.setHeader (node:_http_outgoing:647:3)
    at new ClientRequest (node:_http_client:284:14)
    at Object.request (node:https:360:10)
    at RedirectableRequest._performRequest (/home/woliver99/linux-temp/ford-service-manuals/fetch-ford-service-manuals/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/home/woliver99/linux-temp/ford-service-manuals/fetch-ford-service-manuals/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/home/woliver99/linux-temp/ford-service-manuals/fetch-ford-service-manuals/node_modules/follow-redirects/index.js:487:14)
    at dispatchHttpRequest (/home/woliver99/linux-temp/ford-service-manuals/fetch-ford-service-manuals/node_modules/axios/lib/adapters/http.js:242:25)
    at new Promise (<anonymous>)
    at httpAdapter (/home/woliver99/linux-temp/ford-service-manuals/fetch-ford-service-manuals/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/home/woliver99/linux-temp/ford-service-manuals/fetch-ford-service-manuals/node_modules/axios/lib/core/dispatchRequest.js:58:10) {
  code: 'ERR_INVALID_CHAR'
}
```

is there any solution for this? i can provide more details if you need.

**Comment by woliver99** [comment]
Nevermind i figured it out it was the fact there was a new line after the cookie. There were other problems but i tinkered with the script until it worked. Anyway i realized it doesn't collect all the pages for wireing because of different formats but it seems like it just hasn't been implemented.

**Comment by iamtheyammer** [comment]
Glad you figured it out-- that was definitely the issue.

I added some code yesterday to strip white space, too.
