### ISSUE TITLE
AxiosError using windows

### ISSUE THREAD

**Issue by BrettJohnson71** [iamtheyammer/fetch-ford-service-manuals#26]
Downloading and processing table of contents...
C:\Windows\System32\fetch-ford-service-manuals\node_modules\axios\lib\core\settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 500
    at settle (C:\Windows\System32\fetch-ford-service-manuals\node_modules\axios\lib\core\settle.js:19:12)
    at IncomingMessage.handleStreamEnd (C:\Windows\System32\fetch-ford-service-manuals\node_modules\axios\lib\adapters\http.js:589:11)
    at IncomingMessage.emit (node:events:531:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (C:\Windows\System32\fetch-ford-service-manuals\node_modules\axios\lib\core\Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchTreeAndCover (C:\Windows\System32\fetch-ford-service-manuals\src\workshop\fetchTreeAndCover.ts:14:15)
    at async modernWorkshop (C:\Windows\System32\fetch-ford-service-manuals\src\index.ts:220:41)
    at async run (C:\Windows\System32\fetch-ford-service-manuals\src\index.ts:141:7) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',

**Comment by BrettJohnson71** [comment]
same error occurs using wsl

**Comment by BrettJohnson71** [comment]
initial issue corrected had a 0 instead of a "Capital O" under "book" new issue is 

Saved workshop manual!
Saving wiring manual...
Fetching wiring table of contents...
/mnt/c/Users/Brett/Documents/ford/fetch-ford-service-manuals/.yarn/cache/axios-npm-1.7.2-c89264f6f7-6ae80dda97.zip/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 500

**Comment by BrettJohnson71** [comment]
all is working thank you for developing this.
