### ISSUE TITLE
Unable to handle wiring diagram with "#" in the name

### ISSUE THREAD

**Issue by andyad71** [iamtheyammer/fetch-ford-service-manuals#27]
When trying to pull the wiring diagrams for a 2024 F-150, the script exited with the following error:

```
Saving page 003 of Charging System...
/root/fetch-ford-service-manuals/src/wiring/savePage.ts:94
    await browserPage.goto(`file:///${resolve(svgPath)}`);
                      ^
page.goto: net::ERR_FILE_NOT_FOUND at file:////root/24-F150/Wiring/Charging%20System/003%20POWER%20INVERTER%20#2%20-%202kW.svg
Call log:
  - navigating to "file:////root/24-F150/Wiring/Charging%20System/003%20POWER%20INVERTER%20#2%20-%202kW.svg", waiting until "load"

    at savePage (/root/fetch-ford-service-manuals/src/wiring/savePage.ts:94:23)
    at async saveEntireWiring (/root/fetch-ford-service-manuals/src/wiring/saveEntireWiring.ts:70:7)
    at async run (/root/fetch-ford-service-manuals/src/index.ts:192:5) {
  name: 'Error'
}
```

Checking the directory, the `003 POWER INVERTER #2 - 2kW.svg` file exists

```
root@ford-service:~/fetch-ford-service-manuals# ls ~/24-F150/Wiring/"Charging System"
'001 GASOLINE.pdf'  '002 GASOLINE.pdf'  '003 POWER INVERTER #2 - 2kW.svg'
'001 GASOLINE.svg'  '002 GASOLINE.svg'   pageList.json
```

I'm wondering if the script is being thrown off by the "#" character in the file name.

**Comment by tlovenspclsauce** [comment]
Same issue on files with "#" in the name. 

```Saving page 004 of Charging System...
/home/user1/fetch-ford-service-manuals/src/wiring/savePage.ts:94
    await browserPage.goto(`file:///${resolve(svgPath)}`);
                      ^
page.goto: net::ERR_FILE_NOT_FOUND at file:////home/user1/2024_F-350_SuperDuty/Wiring/Charging%20System/004%20DUAL%20ALTERNATOR%20-%20WITHOUT%20POWER%20INVERTER%20#2.svg
Call log:
  - navigating to "file:////home/user1/2024_F-350_SuperDuty/Wiring/Charging%20System/004%20DUAL%20ALTERNATOR%20-%20WITHOUT%20POWER%20INVERTER%20#2.svg", waiting until "load"

    at savePage (/home/user1/fetch-ford-service-manuals/src/wiring/savePage.ts:94:23)
    at async saveEntireWiring (/home/user1/fetch-ford-service-manuals/src/wiring/saveEntireWiring.ts:70:7)
    at async run (/home/user1/fetch-ford-service-manuals/src/index.ts:192:5) {
  name: 'Error'
}```

**Comment by tlovenspclsauce** [comment]
Figured it out. Take a look at the Pull request and notes.

https://github.com/iamtheyammer/fetch-ford-service-manuals/pull/24
