### ISSUE TITLE
Add the ability to specify a workshop folder to download

### ISSUE THREAD

**Issue by andyad71** [iamtheyammer/fetch-ford-service-manuals#28]
While downloading the workshop library for a 2024 F-150, the script exited with a 503 error after 20-30 minutes of running. It had already downloaded 1.8 GB worth of data and was on the last 10% of pages to download.

```
Downloading manual page Hood Latch Release Cable as HTML, PDF (docID: G2165930)
Encountered an error downloading Hood Latch Release Cable (docID G2165930)
/root/fetch-ford-service-manuals/.yarn/cache/axios-npm-1.7.2-c89264f6f7-6ae80dda97.zip/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 503
    at settle (/root/fetch-ford-service-manuals/.yarn/cache/axios-npm-1.7.2-c89264f6f7-6ae80dda97.zip/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/root/fetch-ford-service-manuals/.yarn/cache/axios-npm-1.7.2-c89264f6f7-6ae80dda97.zip/node_modules/axios/lib/adapters/http.js:589:11)
    at IncomingMessage.emit (node:events:531:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/root/fetch-ford-service-manuals/.yarn/cache/axios-npm-1.7.2-c89264f6f7-6ae80dda97.zip/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchManualPage (/root/fetch-ford-service-manuals/src/workshop/fetchManualPage.ts:27:15)
    at async saveEntireManual (/root/fetch-ford-service-manuals/src/workshop/saveEntireManual.ts:68:26)
    at async saveEntireManual (/root/fetch-ford-service-manuals/src/workshop/saveEntireManual.ts:114:7)
    at async saveEntireManual (/root/fetch-ford-service-manuals/src/workshop/saveEntireManual.ts:114:7)
    at async saveEntireManual (/root/fetch-ford-service-manuals/src/workshop/saveEntireManual.ts:114:7)
    at async saveEntireManual (/root/fetch-ford-service-manuals/src/workshop/saveEntireManual.ts:114:7)
    at async modernWorkshop (/root/fetch-ford-service-manuals/src/index.ts:230:3)
    at async run (/root/fetch-ford-service-manuals/src/index.ts:141:7) {
  code: 'ERR_BAD_RESPONSE',
```

Assuming the 503 was due to some cookie expiration or timeout, I don't see any specific bug initially looking at the console.

However, the only way to move forward from here is to re-download the entire workshop directory from scratch. As it is already taking 30 or more minutes, there's a good chance the script may error out again towards the end of the download.

It would be nice to either pick up where it left off and only download new pages, or be able to specify directories to download so the user could only download the "Body and Paint" information and not the entire workshop library.

**Comment by andyad71** [comment]
I was able to get the full library to download today, so this is just an enhancement request if it would be beneficial.

**Comment by bmwhitetx** [comment]
Another similar problem is having issues with the wiring manual download. If error there, you had to wait until the workshop manual  downloaded again.

I was able to skip downloading the workshop manual and go straight to wiring download by editing the index.ts file under the src folder.
Change line 136 by putting a "!" in front of doWorkshopDownload, e.g.
`  if (!doWorkshopDownload) {`

Would be nice to have a command line switch that does this instead.

But still an awesome program!
