### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

### ISSUE THREAD

**Issue by bridavis** [iamtheyammer/fetch-ford-service-manuals#9]
Great work here, appreciate it.

Getting the following error when starting the wiring manual.

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
    at ClientRequest.setHeader (node:_http_outgoing:576:3)
    at new ClientRequest (node:_http_client:256:14)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (/Users/bridavis/src/fetch-ford-service-manuals/.yarn/__virtual__/follow-redirects-virtual-0541b7cf28/0/cache/follow-redirects-npm-1.14.9-522f191631-f5982e0eb4.zip/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/Users/bridavis/src/fetch-ford-service-manuals/.yarn/__virtual__/follow-redirects-virtual-0541b7cf28/0/cache/follow-redirects-npm-1.14.9-522f191631-f5982e0eb4.zip/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/Users/bridavis/src/fetch-ford-service-manuals/.yarn/__virtual__/follow-redirects-virtual-0541b7cf28/0/cache/follow-redirects-npm-1.14.9-522f191631-f5982e0eb4.zip/node_modules/follow-redirects/index.js:487:14)
    at dispatchHttpRequest (/Users/bridavis/src/fetch-ford-service-manuals/.yarn/cache/axios-npm-0.26.0-ae9d5291c9-d7a8b898f4.zip/node_modules/axios/lib/adapters/http.js:242:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/bridavis/src/fetch-ford-service-manuals/.yarn/cache/axios-npm-0.26.0-ae9d5291c9-d7a8b898f4.zip/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/Users/bridavis/src/fetch-ford-service-manuals/.yarn/cache/axios-npm-0.26.0-ae9d5291c9-d7a8b898f4.zip/node_modules/axios/lib/core/dispatchRequest.js:58:10) {
  code: 'ERR_INVALID_CHAR'
}
```

**Comment by bridavis** [comment]
I did try with both Chrome and FF, and used Raw mode in FF as described in the Readme.

**Comment by iamtheyammer** [comment]
Hm, there must be something odd in there. Try pasting your API key in a regex tester with `[:ascii:]+` - [here's a link to this inside Regex101](https://regex101.com/r/4W0zwp/1).

**Comment by bridavis** [comment]
Unfortunately, my subscription has now expired, but I do have the last cookie string that I was adding to the file. I will try to unicast to you.

**Comment by marniva** [comment]
Had the same issue. Managed to work around it, but now I have: Error: Request failed with status code 500

**Comment by KarelVenter** [comment]
Hi. First off, MANY THANKS for this. VERY VERY handy. I believe I had a similar issue. The script downloaded the Manual successfully but when attempting to download the Wiring Manual I get this output:
Saving wiring manual...
/mnt/c/Windows/System32/fetch-ford-service-manuals/src/index.ts:72
  await wiringContext.addCookies(transformedCookieString);
                      ^
browserContext.addCookies: cookies[4].value: expected string, got number
    at run (/mnt/c/Windows/System32/fetch-ford-service-manuals/src/index.ts:72:23)

I pasted the API Key / Cookie data into Regex101 as you recommended above and the code seemed to have passed?

Any guidance?

**Comment by iamtheyammer** [comment]
Hm, would you mind sending over both params files via email? That way I can try it on my machine— my email is on my profile.

**Comment by mikef187** [comment]
I also got the error 500 issue, but that is actually coming from the FORD server. I just reran the script and it finished.

**Comment by mikef187** [comment]
When creating the cookieString.txt file with ANY text editor I get the ERR_INVALID_CHAR.

When i  create the file with
echo -n ""CONTENT_PERMISSIONS=permi.....; AKA_A2=A" > cookieString.txt
That works.
